### ISSUE TITLE
jupyter-notebook integration

### ISSUE THREAD

**Issue by wagnerc4** [mbarkhau/markdown-aafigure#2]
Hi!
How can integrate with python-markdown nbextensions, and use in markdown cells???
I installed with pip and only can render the diagrams from python code cells:

    from IPython.display import HTML
    from markdown import markdown
    from markdown_aafigure import makeExtension
    
    md = """
    ```aafigure
            +-----+   ^
            |     |   |
        --->+     +---o--->
            |     |   |
            +-----+   V
    ```
    """
    
    HTML(markdown(md, extensions=[makeExtension()]))

**Comment by mbarkhau** [comment]
Good question. Haven't looked into that so I can't say. Do you have other extensions working? Maybe you can see if there is a difference.

**Comment by wagnerc4** [comment]
Thanks for the fast reply.  I don't have other extension of python-markdown working.

**Comment by mbarkhau** [comment]
Earliest I can have a look is Thursday, feel free to report back if you make any progress in the meantime.

**Comment by wagnerc4** [comment]
I look at the source code of both python-markdown packages and it seems to be different packages with the same name!!!  The code of python-markdown inside jupyter nbextensions can be example to make a new package named: jupyter-aafigure... Maybe you like this idea :)

**Comment by mbarkhau** [comment]
Sounds good. There is a related issue that's been open for a while: https://github.com/jupyter/notebook/issues/2300

Using aafigure will require a backend component. If that is too difficult, an alternative approach might be to find a way to integrate a similar javascript library such as mermaid. Here is some prior work that appears to have been abandoned. https://github.com/bollwyvl/nb-mermaid

**Comment by mbarkhau** [comment]
I'm not planning to work on this. I think it's out of scope for the project. Good luck for the other approaches.

**Comment by parthi2929** [comment]
@mbarkhau can you please consider [mermaid](https://mermaidjs.github.io) at least?

**Comment by mbarkhau** [comment]
@parthi2929 consider it for what?

**Comment by parthi2929** [comment]
wrong entry, pl ignore. sorry. was searching for some platform that could support mermaid in jupyter notebooks..
